version: '2'
services:
  ui:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - '3001:3001'
  minner:
    build: ./minner 
